###########################################################################
#
# File:         SConscript (directory: ./py/yapps2)
# Date:         18-Nov-2008
# Author:       Hugh Secker-Walker
# Description:  Tell SCons about our Yapps tools
#
# This file is part of Onyx   http://onyxtools.sourceforge.net
#
# Copyright 2008, 2009 The Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#
###########################################################################

# Tell SCons about our Yapp tools which are used for building other
# .py files in the toolkit, and some of which are needed as runtime by
# the toolkit.

Import('env')

env.PyFile('__init__.py')

# These aren't project files, so not tested.  See README_onyx.txt for details.
# See also py/htkfiles/SConscript where they get used.
yappsrt = env.PyFile('yappsrt.py', no_test=True)
yapps2 = env.PyFile('yapps2.py', no_test=True)
# note: yapps2.py has a glob import from package yappsrt; since we're not sure
# the scanner deals with this glob correctly, and we don't want to modify
# yapps2.py to eliminate the glob, we put in explicit dependencies
env.Depends(yapps2, yappsrt)
env.PyPackageDepends(yapps2, 'yapps2')
