###########################################################################
#
# File:         SConscript (directory: ./py/onyx/dataflow)
# Date:         11-Oct-2007
# Author:       Hugh Secker-Walker
# Description:  Low-level data flow objects
#
# This file is part of Onyx   http://onyxtools.sourceforge.net
#
# Copyright 2007 - 2009 The Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#
###########################################################################

# standard Onyx treatment of Python code
Import('env')
env.DocBuildThisPackage('Dataflow')
env.PyFile('__init__.py')
env.PyFile('cfg.py')
env.PyFile('composecfg.py')
env.PyFile('graph.py')
env.PyFile('simplecfg.py')
env.PyFile('source.py')
env.PyFile('join.py')
env.PyFile('command.py')

env.PyFile('framesynchronous.py', 
           logref='framesynchronous.log-ref', 
           doctest_files=('#' + 'py/onyx/htkfiles/monophones4.mmf',
                          '#' + 'data/htk_r1_adg0_4/adg0_4_sr089.mfc'))
