###########################################################################
#
# File:         SConscript (directory: py/onyx/containers)
# Date:         5-Oct-2007
# Author:       Hugh Secker-Walker
# Description:  Some containers that initialize from a text serialization
#
# This file is part of Onyx   http://onyxtools.sourceforge.net
#
# Copyright 2007 - 2009 The Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#
###########################################################################

# standard Onyx treatment of Python code
Import('env')
env.DocBuildThisPackage("Containers")
env.PyFile('__init__.py')
serializable = env.PyFile('serializable.py')
# serializable.py has non-standard imports, so, for its doctest to work, we have
# to explicitly tell SCons about packages the doctest depends upon
env.PyPackageDepends(serializable, 'onyx.containers')

# note: objectset does non-standard imports, so we have to tell SCons about
# modules that its doctest requires
objectset_deps = (
    'py/onyx/dataflow/graph.py',
    'py/onyx/signalprocessing/delta.py',
    'py/onyx/signalprocessing/scale.py',
    'py/onyx/signalprocessing/spectrum.py',
    'py/onyx/signalprocessing/window.py',
    )
objectset = env.PyFile('objectset.py')
env.PyModuleDepends(objectset, objectset_deps)
env.PyPackageDepends(objectset, ('onyx.dataflow', 'onyx.signalprocessing'))
