###########################################################################
#
# File:         SConscript (directory: ./doc)
# Date:         15-Jan-2009
# Author:       Hugh Secker-Walker
# Description:  Builds documentation
#
# This file is part of Onyx   http://onyxtools.sourceforge.net
#
# Copyright 2009 The Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#
###########################################################################

Import('env')

env.File('SoftwareQuality.txt')
env.File('one_page.pdf')
env.File('thirdParty.txt')
env.File('versioning.txt')
