###########################################################################
#
# File:         SConscript (directory: projects/lm)
# Date:         Fri 28 March 2008
# Author:       Chris White
# Description:  Basic LM (Backoff add lambda for 4 fourgrams)
#
# This file is part of Onyx   http://onyxtools.sourceforge.net
#
# Copyright 2008, 2009 The Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#
###########################################################################

Import('env')
files = env.Flatten(list(env.File(f) for f in ('switchboard-small', 'sample1')))
env.PyFile('__init__.py', no_test=True)
env.PyFile('fileprob.py', doctest_files=files)
env.PyFile('probs.py', doctest_files=files)
