###########################################################################
#
# File:         SConscript (directory: ./py/onyx)
# Date:         4-Oct-2007
# Author:       Hugh Secker-Walker
# Description:  Testing of onyx package
#
# This file is part of Onyx   http://onyxtools.sourceforge.net
#
# Copyright 2007 - 2009 The Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#
###########################################################################


Import('env')
env.DocBuildThisPackage('Base')

env.PyFile('__init__.py', tool_file=True)
env.PyFile('builtin.py')
env.PyFile('doctestmod.py', tool_file=True)
env.PyFile('istext.py')
env.PyFile('lint.py')
env.PyFile('version.py')
