###########################################################################
#
# File:         SConscript (directory: ./doc/images)
# Date:         15-May-2009
# Author:       Ken Basye
# Description:  Images used in toolkit documentation and presentations
#
# This file is part of Onyx   http://onyxtools.sourceforge.net
#
# Copyright 2009 The Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#
###########################################################################

Import('env')

env.File('AlignLattice3.png')
env.File('AlignLattice4.png')
env.File('CodeDependency.png')
env.File('CodeDependencyBW.png')
env.File('CyclicHmm.png')
env.File('DiamondTrainingGraphCompact.png')
env.File('DiamondTrainingGraphCompactDetail.png')
env.File('DiamondTrainingGraphExact.png')
env.File('DiamondTrainingGraphExactConvertedToHmm.png')
env.File('DiamondTrainingGraphExactDetail.png')
env.File('DocPage.png')
env.File('EdgeDualAfter.png')
env.File('EdgeDualBefore.png')
env.File('EpsilonHmmArity2.png')
env.File('EpydocExample.png')
env.File('ForwardHmm4StatesSkip1Compact.png')
env.File('ForwardHmm4StatesSkip1Exact.png')
env.File('GraphExample.png')
env.File('HmmCodeInEmacs.png')
env.File('HmmDotWindow.png')
env.File('MultiWordPhonemeNetwork.png')
env.File('PhonemeHmm.png')
env.File('PronHmmNetwork.png')
env.File('PythonUser.png')
env.File('demo-2009-02-02.py')
env.File('fsdemoflow.png')
env.File('htk_mfcc.dot')
env.File('sphinx_dither.png')
env.File('sphinx_top.png')

