###########################################################################
#
# File:         SConscript (directory: ./projects/chartrecorder)
# Date:         30-Dec-2008
# Author:       Hugh Secker-Walker
# Description:  Chart recorder
#
# This file is part of Onyx   http://onyxtools.sourceforge.net
#
# Copyright 2008 The Johns Hopkins University
#
# Licensed under the Apache License, Version 2.0 (the "License").
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.  See the License for the specific language governing
# permissions and limitations under the License.
#
###########################################################################


# standard Onyx treatment of Python code
Import('env')

# XXX these entries are for testing in templates directory, replace them....
env.PyFile('chart.py', no_test=True)
